export const slugify = (text: string) =>
  text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export const staticProducts = [
  {
    slug: "the-ultimate-business-guide",
    title: "The Ultimate Business Guide",
    description: "A comprehensive deep-dive into modern business strategy and growth frameworks.",
    longDescription: `This comprehensive guide covers everything you need to build, grow, and scale a successful business in today's digital economy.\n\nFrom crafting your value proposition to building scalable systems, this PDF walks you through real-world strategies used by top entrepreneurs and consultants.\n\nPerfect for founders, freelancers, and anyone looking to take their business to the next level.`,
    benefits: [
      "Learn proven business frameworks used by Fortune 500 companies",
      "Step-by-step growth strategies you can implement today",
      "Includes worksheets for goal setting and KPI tracking",
      "Lifetime access with free updates",
    ],
    price: "$19",
    priceNum: 19,
    tag: "Bestseller",
    category: "PDF",
    rating: 5,
    image: "product-pdf",
  },
  {
    slug: "marketing-mastery-course",
    title: "Marketing Mastery Course",
    description: "12-module video course with worksheets to master digital marketing.",
    longDescription: `Master the art and science of digital marketing with this in-depth 12-module course.\n\nEach module includes HD video lessons, actionable worksheets, and real-life case studies. You'll learn SEO, content marketing, paid ads, email funnels, social media strategy, and more.\n\nWhether you're a beginner or intermediate marketer, this course will give you the skills to drive real results.`,
    benefits: [
      "12 HD video modules with downloadable resources",
      "Covers SEO, ads, email marketing, and social media",
      "Real case studies from successful campaigns",
      "Certificate of completion included",
    ],
    price: "$49",
    priceNum: 49,
    tag: "New",
    category: "Course",
    rating: 5,
    image: "product-course",
  },
  {
    slug: "productivity-blueprint-kit",
    title: "Productivity Blueprint Kit",
    description: "Templates, checklists and systems to 10x your daily output.",
    longDescription: `Stop wasting time with scattered workflows. The Productivity Blueprint Kit gives you a proven system for managing tasks, goals, and daily routines.\n\nIncludes Notion templates, Google Sheets trackers, daily planners, and weekly review checklists — everything you need to work smarter.\n\nUsed by over 2,000 professionals to reclaim their time and boost output.`,
    benefits: [
      "Ready-to-use Notion and Google Sheets templates",
      "Daily, weekly, and monthly planning systems",
      "Habit tracker and goal-setting frameworks",
      "Works for individuals and teams",
    ],
    price: "$14",
    priceNum: 14,
    tag: "Popular",
    category: "Template",
    rating: 4,
    image: "product-template",
  },
  {
    slug: "leadership-essentials-pdf",
    title: "Leadership Essentials PDF",
    description: "Core principles every leader needs to inspire teams.",
    longDescription: `Whether you're a first-time manager or a seasoned executive, this guide distills the most important leadership principles into a clear, actionable format.\n\nLearn how to communicate effectively, build trust, handle conflict, and inspire your team to perform at their best.\n\nBacked by research and real-world examples from leaders across industries.`,
    benefits: [
      "Proven frameworks for team management",
      "Communication and conflict resolution strategies",
      "Self-assessment tools for leadership growth",
      "Printable quick-reference cards",
    ],
    price: "$17",
    priceNum: 17,
    category: "PDF",
    rating: 4,
    image: "product-pdf",
  },
  {
    slug: "social-media-playbook",
    title: "Social Media Playbook",
    description: "Step-by-step strategies to grow your audience organically.",
    longDescription: `Grow your social media following the right way — with authentic content, strategic posting, and engagement tactics that actually work.\n\nThis playbook covers Instagram, LinkedIn, TikTok, and Twitter/X with platform-specific strategies, content calendars, and engagement scripts.\n\nIdeal for creators, brands, and small businesses looking to grow without paid ads.`,
    benefits: [
      "Platform-specific growth strategies",
      "30-day content calendar templates",
      "Engagement scripts and hook formulas",
      "Analytics tracking spreadsheets included",
    ],
    price: "$21",
    priceNum: 21,
    category: "Course",
    rating: 5,
    image: "product-course",
  },
  {
    slug: "freelancers-toolkit",
    title: "Freelancer's Toolkit",
    description: "Everything you need to launch your freelance career.",
    longDescription: `Start and grow your freelance business with confidence. This toolkit includes contract templates, proposal templates, invoice generators, and a client onboarding guide.\n\nWhether you're a designer, developer, writer, or consultant — this kit has the essential documents and systems to look professional from day one.\n\nJoin thousands of freelancers who launched successfully with this toolkit.`,
    benefits: [
      "Professional contract and proposal templates",
      "Invoice and expense tracking spreadsheets",
      "Client onboarding checklist and welcome guide",
      "Pricing calculator for setting competitive rates",
    ],
    price: "$12",
    priceNum: 12,
    category: "Template",
    rating: 4,
    image: "product-template",
  },
  {
    slug: "seo-checklist-pro",
    title: "SEO Checklist Pro",
    description: "A complete SEO audit checklist for any website.",
    longDescription: `Rank higher on Google with this comprehensive SEO checklist covering on-page, off-page, and technical SEO.\n\nPerfect for marketers, developers, and business owners who want to ensure their website is fully optimized. Covers metadata, site speed, mobile optimization, backlinks, and more.\n\nUpdated regularly to reflect the latest search engine algorithm changes.`,
    benefits: [
      "100+ point SEO audit checklist",
      "Covers on-page, off-page, and technical SEO",
      "Keyword research worksheet included",
      "Free updates with every algorithm change",
    ],
    price: "$9",
    priceNum: 9,
    tag: "Free Sample",
    category: "PDF",
    rating: 5,
    image: "product-pdf",
  },
  {
    slug: "video-editing-masterclass",
    title: "Video Editing Masterclass",
    description: "From beginner to pro in 8 comprehensive modules.",
    longDescription: `Learn professional video editing from scratch with this hands-on masterclass.\n\nCovers popular tools like DaVinci Resolve and Adobe Premiere Pro. You'll learn cutting, color grading, audio mixing, motion graphics, and export settings for YouTube, TikTok, and more.\n\nIncludes practice footage and project files so you can follow along.`,
    benefits: [
      "8 in-depth video modules with practice files",
      "Covers DaVinci Resolve and Premiere Pro",
      "Color grading and audio mixing tutorials",
      "Export presets for all major platforms",
    ],
    price: "$59",
    priceNum: 59,
    category: "Course",
    rating: 5,
    image: "product-course",
  },
  {
    slug: "social-media-templates-pack",
    title: "Social Media Templates Pack",
    description: "50+ ready-to-use templates for Instagram, LinkedIn & more.",
    longDescription: `Save hours of design work with 50+ professionally designed social media templates.\n\nIncludes Instagram posts, stories, carousels, LinkedIn banners, and TikTok thumbnails. Fully customizable in Canva — just swap your text and images.\n\nPerfect for coaches, creators, and small businesses who want a polished online presence.`,
    benefits: [
      "50+ templates for Instagram, LinkedIn, and TikTok",
      "Fully editable in Canva (free version)",
      "Consistent brand aesthetic across platforms",
      "Includes a style guide for colors and fonts",
    ],
    price: "$24",
    priceNum: 24,
    category: "Template",
    rating: 5,
    image: "product-template",
  },
];

// Image map for resolving static imports
export const imageMap: Record<string, string> = {};

export const getProductBySlug = (slug: string) =>
  staticProducts.find((p) => p.slug === slug);
